
package fi.jyu.jyudirectory.service.imp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JyuDirectoryServiceImpl", targetNamespace = "http://imp.service.jyudirectory.jyu.fi/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JyuDirectoryServiceImpl {


    /**
     * 
     * @return
     *     returns java.util.List<fi.jyu.jyudirectory.service.imp.FacultyModel>
     */
    @WebMethod
    @WebResult(name = "FacultyModelList", targetNamespace = "")
    @RequestWrapper(localName = "getFacultyList", targetNamespace = "http://imp.service.jyudirectory.jyu.fi/", className = "fi.jyu.jyudirectory.service.imp.GetFacultyList")
    @ResponseWrapper(localName = "getFacultyListResponse", targetNamespace = "http://imp.service.jyudirectory.jyu.fi/", className = "fi.jyu.jyudirectory.service.imp.GetFacultyListResponse")
    @Action(input = "http://imp.service.jyudirectory.jyu.fi/JyuDirectoryServiceImpl/getFacultyListRequest", output = "http://imp.service.jyudirectory.jyu.fi/JyuDirectoryServiceImpl/getFacultyListResponse")
    public List<FacultyModel> getFacultyList();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "addFaculty", targetNamespace = "http://imp.service.jyudirectory.jyu.fi/", className = "fi.jyu.jyudirectory.service.imp.AddFaculty")
    @ResponseWrapper(localName = "addFacultyResponse", targetNamespace = "http://imp.service.jyudirectory.jyu.fi/", className = "fi.jyu.jyudirectory.service.imp.AddFacultyResponse")
    @Action(input = "http://imp.service.jyudirectory.jyu.fi/JyuDirectoryServiceImpl/addFacultyRequest", output = "http://imp.service.jyudirectory.jyu.fi/JyuDirectoryServiceImpl/addFacultyResponse")
    public String addFaculty(
        @WebParam(name = "arg0", targetNamespace = "")
        FacultyModel arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "editFaculty", targetNamespace = "http://imp.service.jyudirectory.jyu.fi/", className = "fi.jyu.jyudirectory.service.imp.EditFaculty")
    @ResponseWrapper(localName = "editFacultyResponse", targetNamespace = "http://imp.service.jyudirectory.jyu.fi/", className = "fi.jyu.jyudirectory.service.imp.EditFacultyResponse")
    @Action(input = "http://imp.service.jyudirectory.jyu.fi/JyuDirectoryServiceImpl/editFacultyRequest", output = "http://imp.service.jyudirectory.jyu.fi/JyuDirectoryServiceImpl/editFacultyResponse")
    public String editFaculty(
        @WebParam(name = "arg0", targetNamespace = "")
        FacultyModel arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "deleteFaculty", targetNamespace = "http://imp.service.jyudirectory.jyu.fi/", className = "fi.jyu.jyudirectory.service.imp.DeleteFaculty")
    @ResponseWrapper(localName = "deleteFacultyResponse", targetNamespace = "http://imp.service.jyudirectory.jyu.fi/", className = "fi.jyu.jyudirectory.service.imp.DeleteFacultyResponse")
    @Action(input = "http://imp.service.jyudirectory.jyu.fi/JyuDirectoryServiceImpl/deleteFacultyRequest", output = "http://imp.service.jyudirectory.jyu.fi/JyuDirectoryServiceImpl/deleteFacultyResponse")
    public String deleteFaculty(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns fi.jyu.jyudirectory.service.imp.FacultyModel
     */
    @WebMethod
    @WebResult(name = "FacultyModel", targetNamespace = "")
    @RequestWrapper(localName = "findFacultyById", targetNamespace = "http://imp.service.jyudirectory.jyu.fi/", className = "fi.jyu.jyudirectory.service.imp.FindFacultyById")
    @ResponseWrapper(localName = "findFacultyByIdResponse", targetNamespace = "http://imp.service.jyudirectory.jyu.fi/", className = "fi.jyu.jyudirectory.service.imp.FindFacultyByIdResponse")
    @Action(input = "http://imp.service.jyudirectory.jyu.fi/JyuDirectoryServiceImpl/findFacultyByIdRequest", output = "http://imp.service.jyudirectory.jyu.fi/JyuDirectoryServiceImpl/findFacultyByIdResponse")
    public FacultyModel findFacultyById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
